export const projects = [
  {
    id: 1,
    title: "WithSoul",
    date: "Dec 2021 - Apr 2022",
    description:
      "WithSoul empowers users to tap into the wisdom found within the Bible and various religious texts, harnessing ChatGPT to enrich their daily life content and journaling experiences with the aid of AI and divine knowledge. Additionally, users can stay informed about global news updates and leverage them to enhance their content, while also receiving AI assistance in transforming their ideas into tangible real-life creations.",
    image: "./bible.jpg",
    tags: [
      "Node",
      "React",
      "JavaScript",
      "Next.js",
      "Tailwind",
      "Firebase",
      "ChatGPT",
    ],
    category: "Web app",
    // github: "https://github.com/rishavchanda/Buckoid-Android-App",
    webapp: null,
  },
  {
    id: 2,
    title: "KidBox",
    date: "Dec 2021 - Apr 2022",
    description: "Worked as React Developer for Kidbox startup",
    image: "./kidbox.jpg",
    tags: ["React.js", "JavaScript", "CSS", "SCSS"],
    category: "Web app",
    // github: "https://github.com/rishavchanda/Buckoid-Android-App",
    webapp: "https://kidbox.com/",
  },
  {
    id: 3,
    title: "translator",
    date: "Oct 2021",
    description:
      "This project is about converting the landing page into Next.js with TailwindCss page. Client comes up with a very good landing page and just want the front end development service and i did it with 5 star rating.",
    contributions: [
      "Implement advanced chart libraries like CHART.js.",
      "Create a flexible and customizable dashboard layout with drag-and-drop capabilities.",
    ],
    image: "./figma.jpg",
    tags: [
      "Tailwind",
      "CSS",
      "HTML5",
      " Landing Page.",
      "Next.js",
      "JavaScript",
      "CSS3",
      "React",
      "Front-End Development",
    ],
    category: "web app",
    // github: "https://github.com/rishavchanda/Project-Management-App",
    webapp: "http://www.translator.company/",
  },
  {
    id: 4,
    title: "LifeStyle ",
    date: "2023",
    description:
      "Educational Platform is a comprehensive and innovative online learning solution designed to cater to the diverse needs of students, educators, and institutions. ",
    image: "./education.jpg",
    tags: [
      "React.js",
      "GRAPHQL",
      "TailwindCSS",
      "Jest",
      "Redux",
      "MONGOOSE",
      "NODE.JS",
    ],
    category: "Web app",
    // github: "https://github.com/rishavchanda/Brain-Tumor-Detection",
    webapp: null,
    member: [],
  },

  {
    id: 5,
    title: "A Foot in the Door ",
    date: "Dec 2021 - Apr 2022",
    description:
      "A Foot in the Door is a next-generation job search platform dedicated exclusively to job seekers with 0-5 years of work experience.",
    image: "./foot.jpg",
    tags: [
      "VUE.JS",
      "Material UI",
      "JavaScript",
      "Tailwind",
      "ExpressJS",
      "MongoDB",
      "NodeJS",
    ],
    category: "Web app",
    // github: "https://github.com/rishavchanda/Buckoid-Android-App",
    webapp: null,
  },

  {
    id: 6,
    title: "GeoTourist",
    date: "Jun 2023 - Jul 2023",
    description:
      "This project is about audio tours. The main goal of this app is: when you traveling and you for example near Vienna opera theater, you enable your app and find out about it.In this project I have worked on registration, logination, send emails, on backend,and have made slides, photos, and google maps on frontend side.",
    image: "./geo.jpg",
    tags: [
      "Travel & Hospitality",
      "Google Maps",
      "jQuery",
      "React",
      "Front-End Development",
    ],
    category: "android app",
    // github: "https://github.com/rishavchanda/Job-finder-App",
    webapp: "https://geotourist.com/",
  },
];
